/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myDemoApp;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.ArrayList;
import java.util.Arrays;

class AppTest {
    @Test
   public void testFound() {
      ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 2, 3, 4));
      assertEquals(App.search(array, 4,5),1); // en kucuk doner
    }

    @Test
    public void testFoundSmaller() {
      ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 2, 3, 4));
      assertEquals(App.search(array, 5,2),0);
    }

    @Test
    public void testEmptyArray() {
      ArrayList<Integer> array = new ArrayList<>();
      assertEquals(App.search(array, 1,3),0);
    }

    @Test
    public void testNull() {
      assertEquals(App.search(null,56,2),0);
    }

    @Test

    public void testFOundSame(){
      ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 2, 3, 4));
      assertEquals(App.search(array, 5,5), 0);
    }

}
